#!/bin/bash
# Interactive first-time setup: deploys the server to fly.io, writes
# src/config.h, and builds the .pdx. Safe to re-run — every step asks first.
set -e
cd "$(dirname "$0")"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ask() { # ask <prompt> <default> -> $REPLY
    local prompt="$1" default="$2"
    read -r -p "$prompt [$default]: " REPLY
    REPLY="${REPLY:-$default}"
}
confirm() { # confirm <prompt> -> 0/1
    local yn
    read -r -p "$1 [Y/n]: " yn
    [[ -z "$yn" || "$yn" =~ ^[Yy] ]]
}

bold "Claude Session setup"
echo "Deploys the usage server to fly.io and configures the Playdate app."
echo

# --- prerequisites ---------------------------------------------------------
missing=0
for cmd in fly go openssl; do
    if ! command -v "$cmd" >/dev/null; then
        echo "missing: $cmd" >&2
        missing=1
    fi
done
[ "$missing" = 1 ] && { echo "Install the tools above, then re-run." >&2; exit 1; }
if ! fly auth whoami >/dev/null 2>&1; then
    echo "flyctl is not logged in — run: fly auth login" >&2
    exit 1
fi

# --- questions --------------------------------------------------------------
ask "fly.io app name" "claude-session-$(openssl rand -hex 3)"
APP="$REPLY"
ask "fly.io region (https://fly.io/docs/reference/regions/)" "iad"
REGION="$REPLY"
ask "Playdate bundle ID" "com.example.claudesession"
BUNDLE_ID="$REPLY"
echo

# --- fly app + volume + auth token ------------------------------------------
if fly apps list 2>/dev/null | grep -q "^$APP\b"; then
    echo "fly app '$APP' already exists — reusing it."
else
    bold "Creating fly app '$APP'..."
    fly apps create "$APP"
fi

if ! fly volumes list -a "$APP" 2>/dev/null | grep -q '\bdata\b'; then
    bold "Creating 1 GB volume (persists rotated OAuth tokens)..."
    fly volumes create data --region "$REGION" --size 1 -a "$APP" --yes
fi

if [ -f server/.auth_token.local ]; then
    echo "Reusing existing device token (server/.auth_token.local)."
else
    bold "Generating device auth token..."
    openssl rand -hex 24 > server/.auth_token.local
fi
AUTH_TOKEN="$(cat server/.auth_token.local)"
fly secrets set "AUTH_TOKEN=$AUTH_TOKEN" -a "$APP" --stage

# --- fly.toml ---------------------------------------------------------------
sed -i.bak \
    -e "s/^app = .*/app = \"$APP\"/" \
    -e "s/^primary_region = .*/primary_region = \"$REGION\"/" \
    server/fly.toml
rm -f server/fly.toml.bak

# --- Claude OAuth login ------------------------------------------------------
bold "Claude login"
echo "This creates a dedicated OAuth session for the server (it will NOT touch"
echo "your local Claude Code login). A URL will be printed — open it, approve,"
echo "and paste the code back."
echo
CREDS="$(cd server && go run ./cmd/login)"
fly secrets set "CLAUDE_CREDENTIALS=$CREDS" -a "$APP" --stage

# --- deploy -------------------------------------------------------------------
bold "Deploying to fly.io..."
(cd server && fly deploy --ha=false -a "$APP")

echo
bold "Server is up: https://$APP.fly.dev"
echo "Check: curl -H \"Authorization: Bearer \$(cat server/.auth_token.local)\" https://$APP.fly.dev/api/usage"

# --- Playdate app config ------------------------------------------------------
if [ -f src/config.h ] && ! confirm "src/config.h exists — overwrite?"; then
    echo "Left src/config.h untouched."
else
    cat > src/config.h <<EOF
// Generated by setup.sh. AUTH_TOKEN is the fly.io AUTH_TOKEN secret
// (server/.auth_token.local), NOT an Anthropic API key.
#define SERVER_HOST "$APP.fly.dev"
#define AUTH_TOKEN "$AUTH_TOKEN"
EOF
    echo "Wrote src/config.h."
fi

sed -i.bak "s/^bundleID=.*/bundleID=$BUNDLE_ID/" Source/pdxinfo
rm -f Source/pdxinfo.bak

# --- build ---------------------------------------------------------------------
echo
if confirm "Build the .pdx now (needs the Playdate SDK)?"; then
    ./build.sh
    echo
    bold "Done. Sideload ClaudeSession.pdx via https://play.date/account/sideload"
    echo "or copy it to the device with 'pdutil <serial> datadisk'."
else
    bold "Done. Build later with ./build.sh"
fi
